#!/bin/busybox sh
 
rescue() {
  echo "rescue to shell"
  sh
}
# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
 
# Do your stuff here.
echo "Hi Friends, Welcome to your own Linux!"
#/bin/busybox sh
 
# Mount the root filesystem.
mount -o rw /dev/sda1 /mnt/root || rescue
 
# Clean up.
umount /proc
umount /sys
 
# Boot the real thing.
exec switch_root /mnt/root /sbin/init || rescue
